In [ ]:
# 26-10-2026

In [6]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Tanishk\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Tanishk\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Tanishk\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Tanishk\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Tanishk\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import numpy as np
import pandas as pd

# pandas is used for the data manipulation task

Series -- 
it is basically a single column or row the dimention of series will be 1d so this is how we identify series

dataFrame:- it is a collection/combination of multiple/more than 1 series

In [10]:
# 27-10-2026

# how we create series


a=pd.Series([12,45,67])
print(a)
print(a.dtype)
print(type(a))

0    12
1    45
2    67
dtype: int64
int64
<class 'pandas.Series'>

In [11]:
# how to create series using numpy array

arr1=np.array([1,2,3,4,5,6])
print(arr1.ndim)
print(type(arr1))

s=pd.Series(arr1)
print(type(s))
print(s)

1
<class 'numpy.ndarray'>
<class 'pandas.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [15]:
# to convert dictionaries in Series
dic={
    "marks":[30,50,60,70,90,100]
}

s=pd.Series(dic)
print(dic)
print(s)
print(type(s))
print(s.dtype)

{'marks': [30, 50, 60, 70, 90, 100]}
marks    [30, 50, 60, 70, 90, 100]
dtype: object
<class 'pandas.Series'>
object

In [17]:

arr=np.arange(1,11)
s=pd.Series(arr)

print(arr)
print(s)
print(s.dtype)
print(s.shape)
print(s.size)
print(s.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
int64
(10,)
10
1

In [18]:
# how to give name to the series
s=pd.Series(arr,name="Tanishk's Series")
print(s)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Tanishk's Series, dtype: int64

In [19]:
# how to give custom indexing
arr=np.arange(1,6)
s=pd.Series(arr,index=["A","B","C","D","E"])
print(s)

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [21]:
arr1=np.arange(10,100,10)
arr2=np.arange(1,10)
s=pd.Series(arr2,index=arr1)
print(s)

10    1
20    2
30    3
40    4
50    5
60    6
70    7
80    8
90    9
dtype: int64

# DataFrames:-

In [24]:
# how to create DataFrames from Dictionaries

d={
    "English":[34,45,56,67],
    "Hindi":[34,45,56,67],
    "Maths":[34,45,56,67],
    "Science":[34,45,56,67]
}
df=pd.DataFrame(d,index=[1,2,3,4])
print(df)
display(df)

   English  Hindi  Maths  Science
1       34     34     34       34
2       45     45     45       45
3       56     56     56       56
4       67     67     67       67

   English  Hindi  Maths  Science
1       34     34     34       34
2       45     45     45       45
3       56     56     56       56
4       67     67     67       67

In [8]:
d={
    "English":[34,90,56,67],
    "Hindi":[34,45,80,67],
    "Maths":[34,87,56,67],
    "Science":[98,45,34,67],
    "Python":[12,89,67,45]
}

DF=pd.DataFrame(d,index=["Tanishk","Bhupendra","Avibh","Sameer"])
print(DF)
print()
display(DF)

           English  Hindi  Maths  Science  Python
Tanishk         34     34     34       98      12
Bhupendra       90     45     87       45      89
Avibh           56     80     56       34      67
Sameer          67     67     67       67      45

           English  Hindi  Maths  Science  Python
Tanishk         34     34     34       98      12
Bhupendra       90     45     87       45      89
Avibh           56     80     56       34      67
Sameer          67     67     67       67      45

           English  Hindi  Maths  Science
Tanishk         34     34     34       98
Bhupendra       90     45     87       45
Avibh           56     80     56       34
Sameer          67     67     67       67

In [9]:
# 28-10-2026

In [11]:
# how to load external dataset in pandas:-

# r automatically convert \ into / in backend

data=pd.read_excel(r"C:\Users\Tanishk\Downloads\pandas 4000 data.xlsx")

In [12]:
df=pd.DataFrame(data)
display(df)

,Person ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,1,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,11,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,6,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,6,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,10,ES-2012-4934238,2012-02-02,2012-02-05,First Class,JH-15820,John Huston,Consumer,Hamburg,Hamburg,...,TEC-PH-10004910,Technology,Phones,"Samsung Signal Booster, Full Size",965.160,7,0.0,463.2600,253.09,High
659,10,IT-2013-5930911,2013-03-19,2013-03-19,Same Day,MV-17485,Mark Van Huff,Consumer,Saint-Chamond,Rhône-Alpes,...,OFF-ST-10000288,Office Supplies,Storage,"Fellowes Lockers, Industrial",748.116,4,0.1,282.5160,253.03,Critical
660,6,ES-2012-2674466,2012-03-21,2012-03-23,Second Class,JW-15955,Joni Wasserman,Consumer,Fontenay-aux-Roses,Ile-de-France,...,FUR-BO-10004844,Furniture,Bookcases,"Sauder Corner Shelving, Mobile",943.866,7,0.1,209.7060,252.90,Critical
661,12,IN-2014-54708,2014-05-24,2014-05-29,Second Class,LA-16780,Laura Armstrong,Corporate,Baotou,Inner Mongolia,...,FUR-BO-10001822,Furniture,Bookcases,"Dania Library with Doors, Metal",1447.440,4,0.0,43.3200,252.36,Medium
662,10,ES-2013-5085939,2013-06-14,2013-06-16,First Class,FM-14215,Filia McAdams,Corporate,Prato,Tuscany,...,TEC-AC-10003265,Technology,Accessories,"Belkin Router, Bluetooth",1552.500,6,0.0,62.1000,252.17,Medium

In [13]:
# data analysis and inspection:-

# info function

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Person ID       663 non-null    int64
 1   Order ID        663 non-null    str
 2   Order Date      663 non-null    datetime64[us]
 3   Ship Date       663 non-null    datetime64[us]
 4   Ship Mode       663 non-null    str
 5   Customer ID     663 non-null    str
 6   Customer Name   663 non-null    str
 7   Segment         663 non-null    str
 8   City            663 non-null    str
 9   State           663 non-null    str
 10  Country         663 non-null    str
 11  Postal Code     130 non-null    float64
 12  Market          663 non-null    str
 13  Region          663 non-null    str
 14  Product ID      663 non-null    str
 15  Category        663 non-null    str
 16  Sub-Category    663 non-null    str
 17  Product Name    663 non-null    str
 18  Sales           663 non-null    float64
 19  Quantity        663 non-null    int64
 20  Discount        663 non-null    float64
 21  Profit          663 non-null    float64
 22  Shipping Cost   663 non-null    float64
 23  Order Priority  663 non-null    str
dtypes: datetime64[us](2), float64(5), int64(2), str(15)
memory usage: 230.9 KB

In [16]:
print(df.shape)
print(df.size)

(663, 24)
15912

In [19]:
# how to load csv dataset:-

df=pd.read_csv(r"C:\Users\Tanishk\Downloads\customers-1000.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   str
 2   First Name         1000 non-null   str
 3   Last Name          1000 non-null   str
 4   Company            1000 non-null   str
 5   City               1000 non-null   str
 6   Country            1000 non-null   str
 7   Phone 1            1000 non-null   str
 8   Phone 2            1000 non-null   str
 9   Email              1000 non-null   str
 10  Subscription Date  1000 non-null   str
 11  Website            1000 non-null   str
dtypes: int64(1), str(11)
memory usage: 244.8 KB

In [20]:
print(df.shape)
print(df.size)

(1000, 12)
12000

In [ ]:
# how to load SQL dataset:-

df=pd.DataFrame(pd.read_sql(r""))
df.info()